<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exploratory Data Analysis (EDA) in Sport and Exercise Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Data_Exploration_Techniques_files/libs/clipboard/clipboard.min.js"></script>
<script src="Data_Exploration_Techniques_files/libs/quarto-html/quarto.js"></script>
<script src="Data_Exploration_Techniques_files/libs/quarto-html/popper.min.js"></script>
<script src="Data_Exploration_Techniques_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Data_Exploration_Techniques_files/libs/quarto-html/anchor.min.js"></script>
<link href="Data_Exploration_Techniques_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Data_Exploration_Techniques_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Data_Exploration_Techniques_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Data_Exploration_Techniques_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Data_Exploration_Techniques_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes"><span class="header-section-number">1</span> Learning Outcomes</a></li>
  <li><a href="#introduction-to-exploratory-data-analysis-eda-in-sport-and-exercise-science" id="toc-introduction-to-exploratory-data-analysis-eda-in-sport-and-exercise-science" class="nav-link" data-scroll-target="#introduction-to-exploratory-data-analysis-eda-in-sport-and-exercise-science"><span class="header-section-number">2</span> Introduction to Exploratory Data Analysis (EDA) in Sport and Exercise Science</a>
  <ul class="collapse">
  <li><a href="#what-is-exploratory-data-analysis" id="toc-what-is-exploratory-data-analysis" class="nav-link" data-scroll-target="#what-is-exploratory-data-analysis"><span class="header-section-number">2.1</span> What is Exploratory Data Analysis?</a></li>
  <li><a href="#why-eda-matters-in-sports-science" id="toc-why-eda-matters-in-sports-science" class="nav-link" data-scroll-target="#why-eda-matters-in-sports-science"><span class="header-section-number">2.2</span> Why EDA Matters in Sports Science</a></li>
  <li><a href="#techniques-and-tools-for-eda" id="toc-techniques-and-tools-for-eda" class="nav-link" data-scroll-target="#techniques-and-tools-for-eda"><span class="header-section-number">2.3</span> Techniques and Tools for EDA</a></li>
  <li><a href="#eda-as-a-cyclical-process" id="toc-eda-as-a-cyclical-process" class="nav-link" data-scroll-target="#eda-as-a-cyclical-process"><span class="header-section-number">2.4</span> EDA as a Cyclical Process</a></li>
  </ul></li>
  <li><a href="#loading-and-exploring-the-hbmasssynth-dataset" id="toc-loading-and-exploring-the-hbmasssynth-dataset" class="nav-link" data-scroll-target="#loading-and-exploring-the-hbmasssynth-dataset"><span class="header-section-number">3</span> Loading and Exploring the HbmassSynth Dataset</a>
  <ul class="collapse">
  <li><a href="#understanding-the-dataset" id="toc-understanding-the-dataset" class="nav-link" data-scroll-target="#understanding-the-dataset"><span class="header-section-number">3.1</span> Understanding the Dataset</a></li>
  <li><a href="#loading-the-dataset" id="toc-loading-the-dataset" class="nav-link" data-scroll-target="#loading-the-dataset"><span class="header-section-number">3.2</span> Loading the Dataset</a></li>
  <li><a href="#overview-of-variables" id="toc-overview-of-variables" class="nav-link" data-scroll-target="#overview-of-variables"><span class="header-section-number">3.3</span> Overview of Variables</a></li>
  <li><a href="#story-behind-the-data" id="toc-story-behind-the-data" class="nav-link" data-scroll-target="#story-behind-the-data"><span class="header-section-number">3.4</span> Story Behind the Data</a></li>
  <li><a href="#separating-pre-and-post-exposure-data" id="toc-separating-pre-and-post-exposure-data" class="nav-link" data-scroll-target="#separating-pre-and-post-exposure-data"><span class="header-section-number">3.5</span> Separating Pre and Post-Exposure Data</a></li>
  </ul></li>
  <li><a href="#univariate-analysis" id="toc-univariate-analysis" class="nav-link" data-scroll-target="#univariate-analysis"><span class="header-section-number">4</span> Univariate Analysis</a>
  <ul class="collapse">
  <li><a href="#descriptive-and-summary-statistics" id="toc-descriptive-and-summary-statistics" class="nav-link" data-scroll-target="#descriptive-and-summary-statistics"><span class="header-section-number">4.1</span> Descriptive and Summary Statistics</a>
  <ul class="collapse">
  <li><a href="#descriptive-statistics-with-r-functions" id="toc-descriptive-statistics-with-r-functions" class="nav-link" data-scroll-target="#descriptive-statistics-with-r-functions"><span class="header-section-number">4.1.1</span> Descriptive Statistics with R Functions</a></li>
  <li><a href="#descriptive-statistics-with-the-skimr-package" id="toc-descriptive-statistics-with-the-skimr-package" class="nav-link" data-scroll-target="#descriptive-statistics-with-the-skimr-package"><span class="header-section-number">4.1.2</span> Descriptive Statistics with the <code>skimr</code> Package</a></li>
  <li><a href="#key-features-to-analyze-in-descriptive-statistics" id="toc-key-features-to-analyze-in-descriptive-statistics" class="nav-link" data-scroll-target="#key-features-to-analyze-in-descriptive-statistics"><span class="header-section-number">4.1.3</span> Key Features to Analyze in Descriptive Statistics</a></li>
  <li><a href="#summary-statistics-for-categorical-data" id="toc-summary-statistics-for-categorical-data" class="nav-link" data-scroll-target="#summary-statistics-for-categorical-data"><span class="header-section-number">4.1.4</span> Summary Statistics for Categorical Data</a></li>
  <li><a href="#handling-missing-data-and-outliers" id="toc-handling-missing-data-and-outliers" class="nav-link" data-scroll-target="#handling-missing-data-and-outliers"><span class="header-section-number">4.1.5</span> Handling Missing Data and Outliers</a></li>
  </ul></li>
  <li><a href="#graphical-analysis-and-variable-distributions" id="toc-graphical-analysis-and-variable-distributions" class="nav-link" data-scroll-target="#graphical-analysis-and-variable-distributions"><span class="header-section-number">4.2</span> Graphical Analysis and Variable Distributions</a>
  <ul class="collapse">
  <li><a href="#visualizing-quantitative-variables-with-histograms" id="toc-visualizing-quantitative-variables-with-histograms" class="nav-link" data-scroll-target="#visualizing-quantitative-variables-with-histograms"><span class="header-section-number">4.2.1</span> Visualizing Quantitative Variables with Histograms</a></li>
  <li><a href="#understanding-distribution-characteristics" id="toc-understanding-distribution-characteristics" class="nav-link" data-scroll-target="#understanding-distribution-characteristics"><span class="header-section-number">4.2.2</span> Understanding Distribution Characteristics</a></li>
  <li><a href="#analyzing-pre-exposure-variable-distributions" id="toc-analyzing-pre-exposure-variable-distributions" class="nav-link" data-scroll-target="#analyzing-pre-exposure-variable-distributions"><span class="header-section-number">4.2.3</span> Analyzing Pre-Exposure Variable Distributions</a></li>
  <li><a href="#visualizing-quantitative-variables-with-box-plots" id="toc-visualizing-quantitative-variables-with-box-plots" class="nav-link" data-scroll-target="#visualizing-quantitative-variables-with-box-plots"><span class="header-section-number">4.2.4</span> Visualizing Quantitative Variables with Box Plots</a></li>
  <li><a href="#visualizing-categorical-variables-with-bar-plots" id="toc-visualizing-categorical-variables-with-bar-plots" class="nav-link" data-scroll-target="#visualizing-categorical-variables-with-bar-plots"><span class="header-section-number">4.2.5</span> Visualizing Categorical Variables with Bar Plots</a></li>
  <li><a href="#comparing-pre-and-post-exposure-variable-distributions" id="toc-comparing-pre-and-post-exposure-variable-distributions" class="nav-link" data-scroll-target="#comparing-pre-and-post-exposure-variable-distributions"><span class="header-section-number">4.2.6</span> Comparing Pre and Post Exposure Variable Distributions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bivariate-and-multivariate-analysis" id="toc-bivariate-and-multivariate-analysis" class="nav-link" data-scroll-target="#bivariate-and-multivariate-analysis"><span class="header-section-number">5</span> Bivariate and Multivariate Analysis</a>
  <ul class="collapse">
  <li><a href="#pairwise-scatter-plots" id="toc-pairwise-scatter-plots" class="nav-link" data-scroll-target="#pairwise-scatter-plots"><span class="header-section-number">5.1</span> Pairwise Scatter Plots</a></li>
  <li><a href="#correlation-matrix" id="toc-correlation-matrix" class="nav-link" data-scroll-target="#correlation-matrix"><span class="header-section-number">5.2</span> Correlation Matrix</a></li>
  <li><a href="#investigating-relationships-with-the-dependent-variable" id="toc-investigating-relationships-with-the-dependent-variable" class="nav-link" data-scroll-target="#investigating-relationships-with-the-dependent-variable"><span class="header-section-number">5.3</span> Investigating Relationships with the Dependent Variable</a></li>
  <li><a href="#visualizing-three-way-relationships" id="toc-visualizing-three-way-relationships" class="nav-link" data-scroll-target="#visualizing-three-way-relationships"><span class="header-section-number">5.4</span> Visualizing Three-Way Relationships</a></li>
  <li><a href="#handling-associated-variables-and-covariance" id="toc-handling-associated-variables-and-covariance" class="nav-link" data-scroll-target="#handling-associated-variables-and-covariance"><span class="header-section-number">5.5</span> Handling Associated Variables and Covariance</a></li>
  <li><a href="#exploring-non-linear-associations" id="toc-exploring-non-linear-associations" class="nav-link" data-scroll-target="#exploring-non-linear-associations"><span class="header-section-number">5.6</span> Exploring Non-linear Associations</a></li>
  <li><a href="#contingency-tables-and-chi-square-statistics" id="toc-contingency-tables-and-chi-square-statistics" class="nav-link" data-scroll-target="#contingency-tables-and-chi-square-statistics"><span class="header-section-number">5.7</span> Contingency Tables and Chi-Square Statistics</a></li>
  <li><a href="#visual-comparisons-of-groups" id="toc-visual-comparisons-of-groups" class="nav-link" data-scroll-target="#visual-comparisons-of-groups"><span class="header-section-number">5.8</span> Visual Comparisons of Groups</a></li>
  </ul></li>
  <li><a href="#conclusion-and-reflection" id="toc-conclusion-and-reflection" class="nav-link" data-scroll-target="#conclusion-and-reflection"><span class="header-section-number">6</span> Conclusion and Reflection</a></li>
  <li><a href="#knowledge-spot-check" id="toc-knowledge-spot-check" class="nav-link" data-scroll-target="#knowledge-spot-check"><span class="header-section-number">7</span> Knowledge Spot-Check</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Data_Exploration_Techniques.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploratory Data Analysis (EDA) in Sport and Exercise Science</h1>
<p class="subtitle lead">Unveiling Patterns and Relationships in Athlete Data</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    Explore the fundamentals of exploratory data analysis (EDA) in the domain of sports science. This practical lesson introduces EDA using R and the speedsR package, focusing on real-world applications in the analysis of athlete data. Gain essential skills in visualizing and interpreting data distributions, correlations, and interactions between variables. Perfect for sports scientists and data analysts, this lesson emphasizes practicality, equipping you with the tools needed to draw meaningful insights from data and apply them effectively in training and performance contexts.
  </div>
</div>

</header>

<div class="callout callout-style-default callout-tip callout-titled" title="Keywords">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Keywords
</div>
</div>
<div class="callout-body-container callout-body">
<p>Exploratory data analysis (EDA), univariate analysis, multivariate analysis, data visualization, statistical analysis, sports science, R, ggplot2, tidyverse, dplyr, gridExtra, moments, GGally, speedsR, correlation, scatter plots, histograms, box plots, bar charts, skewness, kurtosis.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Lesson's Level">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lesson’s Level
</div>
</div>
<div class="callout-body-container callout-body">
<p>The level of this lesson is categorized as <span style="color:#CD7F32">BRONZE</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="**Lesson's Main Idea**">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Lesson’s Main Idea</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Exploratory Data Analysis (EDA) serves as the foundational step in sport science analytics, enabling the uncovering of underlying data structures and key characteristics without preconceived hypotheses.</li>
<li>By mastering EDA techniques in R, practitioners can effectively visualize, analyze, and interpret their data, discovering unexpected patterns and crucial insights that drive evidence-based strategies in sport and exercise science.</li>
</ul>
</div>
</div>
<section id="learning-outcomes" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Learning Outcomes</h1>
<p>By the end of this lesson, you will have developed the ability to:</p>
<ul>
<li><p><strong>Conduct Univariate and Multivariate Analysis</strong>: Perform univariate analysis to understand single-variable distributions and multivariate analysis to explore relationships between multiple variables, applying these insights to sport science data.</p></li>
<li><p><strong>Utilize Graphical and Statistical EDA Techniques</strong>: Master the use of graphical methods such as histograms, box plots, and scatter plots, as well as statistical techniques including correlation and regression analysis to uncover patterns and associations within the data.</p></li>
<li><p><strong>Interpret Distribution Characteristics</strong>: Analyze and interpret key statistical metrics such as skewness and kurtosis to understand the nature of data distributions and identify potential outliers or anomalies.</p></li>
<li><p><strong>Apply EDA in R</strong>: Leverage R programming and its powerful libraries to execute exploratory data analysis, enhancing your analytical skills and improving your decision-making in sport and exercise science contexts.</p></li>
</ul>
</section>
<section id="introduction-to-exploratory-data-analysis-eda-in-sport-and-exercise-science" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction to Exploratory Data Analysis (EDA) in Sport and Exercise Science</h1>
<section id="what-is-exploratory-data-analysis" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="what-is-exploratory-data-analysis"><span class="header-section-number">2.1</span> What is Exploratory Data Analysis?</h2>
<p>Exploratory Data Analysis, commonly known as EDA, is a fundamental process in data science aimed at uncovering the underlying structure of data and its key characteristics. In the context of sport and exercise science, EDA is an invaluable tool that helps practitioners analyze performance metrics, assess athlete health data, and understand trends in sports injuries or training outcomes. By applying EDA, sports scientists can explore data without preconceived hypotheses, enabling them to discover unexpected patterns, identify anomalies, and test assumptions.</p>
</section>
<section id="why-eda-matters-in-sports-science" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="why-eda-matters-in-sports-science"><span class="header-section-number">2.2</span> Why EDA Matters in Sports Science</h2>
<p>In sports analytics, EDA is essential for validating data quality, ensuring accurate analysis, and deriving insights that can influence training programs and game strategies. It allows for the examination of variables and relationships within the data, helping practitioners make informed decisions based on statistical evidence. EDA techniques facilitate a deeper understanding of the data, such as discovering relationships between player performance metrics and outcomes, or evaluating the effectiveness of training regimens.</p>
</section>
<section id="techniques-and-tools-for-eda" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="techniques-and-tools-for-eda"><span class="header-section-number">2.3</span> Techniques and Tools for EDA</h2>
<p>EDA can be broadly classified into several types, each offering different insights:</p>
<p><strong>Univariate Analysis</strong>:</p>
<ul>
<li><strong>Graphical methods</strong>: Histograms, box plots, and stem-and-leaf plots provide a visual summary of single variables, highlighting the distribution, central tendency, and dispersion.</li>
<li><strong>Non-graphical methods</strong>: These involve summary statistics like mean, median, and mode, which help describe the basic features of the data.</li>
</ul>
<p><strong>Bivariate and Multivariate Analysis</strong>:</p>
<ul>
<li><strong>Graphical methods</strong>: Scatter plots, grouped bar plots, and heat maps show the relationship between two or more variables. These are crucial for identifying correlations or interactions between different data aspects, such as the impact of different training loads on athlete performance.</li>
<li><strong>Non-graphical methods</strong>: Techniques such as cross-tabulation and correlation coefficients help quantify the strength and direction of relationships between variables.</li>
</ul>
</section>
<section id="eda-as-a-cyclical-process" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="eda-as-a-cyclical-process"><span class="header-section-number">2.4</span> EDA as a Cyclical Process</h2>
<p>EDA is not a one-time task but a cyclical process that evolves with the analysis. As new data comes in or as further analysis is conducted, sports scientists may return to EDA to refine their models or to explore new hypotheses. This iterative nature ensures that the insights remain relevant and that the models continually improve, aligning with the dynamic and evolving field of sports science.</p>
<p>For practitioners in sport and exercise science, mastering EDA is crucial for making the most of their data. Whether it’s improving team performance, optimizing athlete health, or predicting future trends, EDA provides a robust foundation for any further analysis or modeling. Through the practical application of EDA techniques, sports scientists can ensure that their conclusions and recommendations are well-supported by data.</p>
<p>In this lesson, we will explore simple, real-world examples of how these EDA techniques can be applied using R programming language to sports data, providing a hands-on understanding of each method’s utility and impact.</p>
</section>
</section>
<section id="loading-and-exploring-the-hbmasssynth-dataset" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Loading and Exploring the HbmassSynth Dataset</h1>
<p>In our EDA lesson, we will explore the <code>HbmassSynth</code> dataset from the <code>speedsR</code> package, an R data package specifically designed for the SPEEDS project. This package provides a collection of sports-specific datasets, streamlining access for analysis and research in the sports science context. The <code>HbmassSynth</code> dataset offers valuable insights into the effects of moderate altitude exposure and iron supplementation on hematological variables in endurance athletes. Before we dive into exploratory data analysis, let’s first load and familiarize ourselves with this dataset. For more information about the <code>speedsR</code> package and its offerings, please visit the dedicated page on our platform <a href="https://speeds.quarto.pub/speeds/speedsR_data_package.html">here</a>.</p>
<section id="understanding-the-dataset" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="understanding-the-dataset"><span class="header-section-number">3.1</span> Understanding the Dataset</h2>
<p>The <code>HbmassSynth</code> dataset represents a synthetic study aimed at investigating how oral iron supplementation affects hemoglobin mass (Hbmass) and iron parameters after 2–4 weeks of moderate altitude exposure. Understanding these relationships is crucial for optimizing athlete performance and health.</p>
</section>
<section id="loading-the-dataset" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="loading-the-dataset"><span class="header-section-number">3.2</span> Loading the Dataset</h2>
<p>First, we’ll load the dataset into our R environment. We will use the <code>speedsR</code> package, which contains the dataset in a tibble format. Tibbles are enhanced versions of R dataframes provided by the <code>tidyverse</code>, making them more user-friendly for data manipulation.</p>
<p>Here is how to load and initially explore the <code>HbmassSynth</code> dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the speedsR package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(speedsR)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Access and assign the dataset to a variable</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>hbmass_data <span class="ot">&lt;-</span> HbmassSynth</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the dataset to understand its structure</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hbmass_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
     ID TIME  SEX   SUP_DOSE    BM   FER    FE  TSAT TRANS  AHBM  RHBM
  &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 0     1     0         97.4  150.  18.7    30   2.6  1265  13.0
2     2 0     1     0         65.7  228.  22.1    43   3.2   904  13.8
3     3 0     0     0         59.2  134.  17.1    36   2.5   649  11.0
4     4 0     1     0         93.2  161.  25      34   2.9  1292  13.9
5     5 0     1     0         93.2  136.  25.1    34   2.6  1292  13.9
6     6 0     0     0         56.8  134.  19.5    23   3.3   660  11.6</code></pre>
</div>
</div>
<p>This code snippet loads the <code>HbmassSynth</code> dataset and displays its first few rows, providing a preview of the data’s structure and the types of variables it contains.</p>
</section>
<section id="overview-of-variables" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="overview-of-variables"><span class="header-section-number">3.3</span> Overview of Variables</h2>
<p>The dataset contains several key variables, each representing different hematological measures and participant characteristics:</p>
<p><strong>ID</strong>: Participant identifier, a unique integer for each athlete.</p>
<p><strong>TIME</strong>: Categorical factor indicating the timing of the measurement (0 = Pre-exposure, 1 = Post-exposure).</p>
<p><strong>SEX</strong>: Categorical factor denoting sex (0 = Female, 1 = Male).</p>
<p><strong>SUP_DOSE</strong>: Categorical factor representing the dose of oral iron supplement in milligrams (0 = None, 1 = 105 mg, 2 = 210 mg).</p>
<p><strong>BM</strong>: Body mass in kilograms.</p>
<p><strong>FER</strong>: Ferritin level in micrograms per litre, indicating iron storage.</p>
<p><strong>FE</strong>: Iron level in micrograms per litre.</p>
<p><strong>TSAT</strong>: Transferrin Saturation percentage, a measure of iron availability.</p>
<p><strong>TRANS</strong>: Transferrin in grams per litre, related to iron transport.</p>
<p><strong>AHBM</strong>: Absolute Hemoglobin Mass in grams, the primary variable of interest.</p>
<p><strong>RHBM</strong>: Relative Hemoglobin Mass, computed as AHBM divided by body mass (g/kg).</p>
</section>
<section id="story-behind-the-data" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="story-behind-the-data"><span class="header-section-number">3.4</span> Story Behind the Data</h2>
<p>The purpose of collecting this data was to assess the impact of altitude training combined with iron supplementation on key hematological markers. This type of analysis is critical for sports scientists and coaches to understand how to enhance athletic performance and manage athlete health effectively under different training conditions.</p>
<p>The dataset’s richness allows for multiple avenues of exploration, from assessing the basic impacts of altitude and supplementation on athlete health to more nuanced analyses of how these factors interact with sex and body mass. Each variable provides a specific lens through which to view the athlete’s physiological responses, offering insights that can guide training and recovery strategies.</p>
<p>In the following sections, we will delve deeper into this dataset using various exploratory data analysis techniques to uncover patterns and trends in the data.</p>
</section>
<section id="separating-pre-and-post-exposure-data" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="separating-pre-and-post-exposure-data"><span class="header-section-number">3.5</span> Separating Pre and Post-Exposure Data</h2>
<p>In the <code>HbmassSynth</code> dataset, the <code>TIME</code> variable categorizes data into two groups representing measurements taken before (<code>TIME = 0</code>) and after (<code>TIME = 1</code>) the athletes’ exposure to moderate altitude. This differentiation allows us to analyze how hematological variables change due to the intervention.</p>
<p>To effectively analyze these changes, we’ll first separate the dataset into two parts based on the <code>TIME</code> variable. This will enable us to handle and analyze pre-exposure and post-exposure data independently, providing clearer insights into the effects of altitude exposure on the athletes.</p>
<p>Here’s how we can separate the dataset and assign each subset to a descriptive variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate the data into pre-exposure and post-exposure datasets</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pre_exposure_data <span class="ot">&lt;-</span> hbmass_data[hbmass_data<span class="sc">$</span>TIME <span class="sc">==</span> <span class="dv">0</span>, ]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>post_exposure_data <span class="ot">&lt;-</span> hbmass_data[hbmass_data<span class="sc">$</span>TIME <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the structure of the separated datasets</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pre_exposure_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
     ID TIME  SEX   SUP_DOSE    BM   FER    FE  TSAT TRANS  AHBM  RHBM
  &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 0     1     0         97.4  150.  18.7    30   2.6  1265  13.0
2     2 0     1     0         65.7  228.  22.1    43   3.2   904  13.8
3     3 0     0     0         59.2  134.  17.1    36   2.5   649  11.0
4     4 0     1     0         93.2  161.  25      34   2.9  1292  13.9
5     5 0     1     0         93.2  136.  25.1    34   2.6  1292  13.9
6     6 0     0     0         56.8  134.  19.5    23   3.3   660  11.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(post_exposure_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
     ID TIME  SEX   SUP_DOSE    BM   FER    FE  TSAT TRANS  AHBM  RHBM
  &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 1     1     0         94.1  63    13.1    21   1.3  1356  14.4
2     2 1     1     0         94.1 120    13.1    14   2.6  1387  14.7
3     3 1     0     0         56   144.   27.8    12   2.3   687  12.3
4     4 1     1     0         66.8 119    12.7    15   2.9   875  13.1
5     5 1     1     0         73    87.8  13.1    18   2.5  1113  15.2
6     6 1     0     0         51   120    37.4    40   1.3   637  12.5</code></pre>
</div>
</div>
<p>For simplicity and conciseness of this lesson, we will primarily focus on the pre-exposure data. This approach allows us to establish a baseline understanding of the hematological variables before any altitude intervention. However, later in the lesson, we will compare key parameters between the pre-exposure and post-exposure datasets.</p>
<p>By separating the dataset in this way, we can maintain a clear and structured approach to our exploratory data analysis, ensuring that our findings are both comprehensive and easy to understand.</p>
</section>
</section>
<section id="univariate-analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Univariate Analysis</h1>
<section id="descriptive-and-summary-statistics" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="descriptive-and-summary-statistics"><span class="header-section-number">4.1</span> Descriptive and Summary Statistics</h2>
<p>In this section of this EDA lesson, we will focus on univariate analysis of the pre-exposure data from the <code>HbmassSynth</code> dataset. Univariate analysis allows us to understand the distribution, central tendency, and variability of individual variables independently. We will start with non-graphical methods to get a thorough understanding of each variable’s characteristics.</p>
<section id="descriptive-statistics-with-r-functions" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="descriptive-statistics-with-r-functions"><span class="header-section-number">4.1.1</span> Descriptive Statistics with R Functions</h3>
<p>One common method to obtain descriptive statistics in R is by using the <code>summary()</code> function, which provides a quick overview of the minimum, maximum, median, mean, and the 1st and 3rd quartiles of numeric data. This function can help identify potential outliers and give a concise snapshot of data distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics of the pre-exposure data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pre_exposure_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID           TIME       SEX     SUP_DOSE         BM       
 Min.   :  1.00   0   :178   0   :80   0   : 15   Min.   :47.00  
 1st Qu.: 45.25   1   :  0   1   :98   1   :144   1st Qu.:59.23  
 Median : 89.50   NA's:  1   NA's: 1   2   : 19   Median :65.55  
 Mean   : 89.50                        NA's:  1   Mean   :66.51  
 3rd Qu.:133.75                                   3rd Qu.:72.90  
 Max.   :178.00                                   Max.   :97.40  
 NA's   :1                                        NA's   :1      
      FER               FE             TSAT           TRANS      
 Min.   : 12.30   Min.   : 6.10   Min.   : 3.10   Min.   :1.300  
 1st Qu.: 44.17   1st Qu.:14.47   1st Qu.:20.00   1st Qu.:2.500  
 Median : 66.65   Median :17.05   Median :26.00   Median :2.800  
 Mean   : 75.06   Mean   :19.41   Mean   :28.64   Mean   :2.777  
 3rd Qu.: 98.38   3rd Qu.:24.14   3rd Qu.:35.00   3rd Qu.:3.100  
 Max.   :227.80   Max.   :40.50   Max.   :88.00   Max.   :4.100  
 NA's   :1        NA's   :1       NA's   :1       NA's   :1      
      AHBM             RHBM       
 Min.   : 488.0   Min.   : 7.737  
 1st Qu.: 686.2   1st Qu.:11.057  
 Median : 810.0   Median :13.124  
 Mean   : 845.2   Mean   :12.668  
 3rd Qu.: 975.0   3rd Qu.:14.054  
 Max.   :1424.0   Max.   :18.605  
 NA's   :1        NA's   :1       </code></pre>
</div>
</div>
</section>
<section id="descriptive-statistics-with-the-skimr-package" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="descriptive-statistics-with-the-skimr-package"><span class="header-section-number">4.1.2</span> Descriptive Statistics with the <code>skimr</code> Package</h3>
<p>While <code>summary()</code> provides basic statistical insights, the <code>skimr</code> package offers a more enhanced and visually informative summary. The <code>skim()</code> function from <code>skimr</code> generates detailed descriptive statistics, including the mean, standard deviation, missing value counts, and histograms for quick visual reference, enhancing our understanding of the data’s distribution. If you don’t have the <code>skimr</code> package installed in your R environment, you can do so with <code>install.packages("skimr")</code>. Once installed, you can apply the <code>skim()</code> function to your dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Using skim() to obtain detailed summary statistics</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(pre_exposure_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">pre_exposure_data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">179</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TIME</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">0: 178, 1: 0</td>
</tr>
<tr class="even">
<td style="text-align: left;">SEX</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">1: 98, 0: 80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SUP_DOSE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">1: 144, 2: 19, 0: 15</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ID</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">89.50</td>
<td style="text-align: right;">51.53</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">45.25</td>
<td style="text-align: right;">89.50</td>
<td style="text-align: right;">133.75</td>
<td style="text-align: right;">178.0</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">BM</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">66.51</td>
<td style="text-align: right;">10.71</td>
<td style="text-align: right;">47.00</td>
<td style="text-align: right;">59.23</td>
<td style="text-align: right;">65.55</td>
<td style="text-align: right;">72.90</td>
<td style="text-align: right;">97.4</td>
<td style="text-align: left;">▅▇▆▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">75.06</td>
<td style="text-align: right;">39.86</td>
<td style="text-align: right;">12.30</td>
<td style="text-align: right;">44.17</td>
<td style="text-align: right;">66.65</td>
<td style="text-align: right;">98.38</td>
<td style="text-align: right;">227.8</td>
<td style="text-align: left;">▇▇▃▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">FE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">19.41</td>
<td style="text-align: right;">7.45</td>
<td style="text-align: right;">6.10</td>
<td style="text-align: right;">14.48</td>
<td style="text-align: right;">17.05</td>
<td style="text-align: right;">24.14</td>
<td style="text-align: right;">40.5</td>
<td style="text-align: left;">▃▇▃▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TSAT</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">28.64</td>
<td style="text-align: right;">13.73</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">26.00</td>
<td style="text-align: right;">35.00</td>
<td style="text-align: right;">88.0</td>
<td style="text-align: left;">▃▇▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRANS</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: left;">▁▃▇▆▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AHBM</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">845.16</td>
<td style="text-align: right;">200.42</td>
<td style="text-align: right;">488.00</td>
<td style="text-align: right;">686.25</td>
<td style="text-align: right;">810.00</td>
<td style="text-align: right;">975.00</td>
<td style="text-align: right;">1424.0</td>
<td style="text-align: left;">▅▇▇▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">RHBM</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">12.67</td>
<td style="text-align: right;">1.93</td>
<td style="text-align: right;">7.74</td>
<td style="text-align: right;">11.06</td>
<td style="text-align: right;">13.12</td>
<td style="text-align: right;">14.05</td>
<td style="text-align: right;">18.6</td>
<td style="text-align: left;">▂▅▇▃▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The advantage of <code>skimr</code> over traditional methods like <code>summary()</code> is its ability to provide histograms and frequency tables directly in the console, making it a powerful tool for initial data review.</p>
</section>
<section id="key-features-to-analyze-in-descriptive-statistics" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="key-features-to-analyze-in-descriptive-statistics"><span class="header-section-number">4.1.3</span> Key Features to Analyze in Descriptive Statistics</h3>
<p><strong>Central Tendency Statistics</strong></p>
<ul>
<li><strong>Mean</strong>: The average of the data.
<ul>
<li><code>mean(pre_exposure_data$variable, na.rm = TRUE)</code></li>
</ul></li>
<li><strong>Median</strong>: The middle value in the data.
<ul>
<li><code>median(pre_exposure_data$variable, na.rm = TRUE)</code></li>
</ul></li>
<li><strong>Mode</strong>: The most frequently occurring value in the data.
<ul>
<li>R does not have a built-in function for mode, but it can be calculated using custom functions or packages like <code>DescTools</code>.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example of calculating the mean and median</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pre_exposure_data<span class="sc">$</span>AHBM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 845.1573</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(pre_exposure_data<span class="sc">$</span>AHBM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 810</code></pre>
</div>
</div>
<p><strong>Spread Statistics</strong></p>
<ul>
<li><strong>Range</strong>: The difference between the maximum and minimum.
<ul>
<li><code>max(pre_exposure_data$variable) - min(pre_exposure_data$variable)</code></li>
</ul></li>
<li><strong>Interquartile Range (IQR)</strong>: Measures the statistical spread of the middle 50% of the data.
<ul>
<li><code>IQR(pre_exposure_data$variable, na.rm = TRUE)</code></li>
</ul></li>
<li><strong>Variance</strong>: Measures the variability from the mean.
<ul>
<li><code>var(pre_exposure_data$variable, na.rm = TRUE)</code></li>
</ul></li>
<li><strong>Standard Deviation</strong>: Square root of the variance.
<ul>
<li><code>sd(pre_exposure_data$variable, na.rm = TRUE)</code></li>
</ul></li>
<li><strong>Mean Absolute Deviation (MAD)</strong>: Average distance between each data point and the mean.
<ul>
<li><code>mad(pre_exposure_data$variable, na.rm = TRUE)</code></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example of calculating variance and standard deviation</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(pre_exposure_data<span class="sc">$</span>AHBM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40168.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(pre_exposure_data<span class="sc">$</span>AHBM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 200.4213</code></pre>
</div>
</div>
</section>
<section id="summary-statistics-for-categorical-data" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="summary-statistics-for-categorical-data"><span class="header-section-number">4.1.4</span> Summary Statistics for Categorical Data</h3>
<p>For categorical variables, summarizing the distribution involves calculating the frequency or proportion of observations in each category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency count of categorical data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pre_exposure_data<span class="sc">$</span>SEX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 0  1 
80 98 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of categories</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(pre_exposure_data<span class="sc">$</span>SEX))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.4494382 0.5505618 </code></pre>
</div>
</div>
<p>This approach to univariate analysis provides a solid foundation for understanding each variable independently, setting the stage for deeper multivariate analysis, which we will explore in subsequent sections.</p>
</section>
<section id="handling-missing-data-and-outliers" class="level3" data-number="4.1.5">
<h3 data-number="4.1.5" class="anchored" data-anchor-id="handling-missing-data-and-outliers"><span class="header-section-number">4.1.5</span> Handling Missing Data and Outliers</h3>
<p>Understanding the impact of missing values and outliers is a pivotal step in exploratory data analysis. Missing data can lead to biased estimates and reduce the statistical power of your analysis, while outliers can significantly skew results. It’s crucial to identify and address these issues to ensure the accuracy and reliability of your findings.</p>
<p>However, in the context of our current lesson using the <code>HbmassSynth</code> dataset, these concerns have already been mitigated. The dataset is synthetic, derived from real-world data with all missing values imputed prior to synthesis, which ensures a complete dataset for our exploratory purposes. Additionally, potential outliers have been addressed to create a representative and analytically convenient dataset.</p>
<p>For those interested in understanding the methods of handling missing data and outliers, we have dedicated lessons that delve into these topics. These lessons will equip you with the knowledge and techniques to tackle these issues effectively in your datasets:</p>
<ul>
<li>For comprehensive strategies on handling missing values and outliers, please refer to our lesson on <a href="https://speeds.quarto.pub/speeds/Handling_Missing_Data_and_Outliers.html">Data Integrity: Handling Missing Data and Outliers</a>.</li>
<li>To learn about a practical example on how to impute missing values, as well as generating synthetic datasets, explore our lesson on <a href="https://speeds.quarto.pub/speeds/Synthetic_Data_Generation_With_synthpop.html">Data Privacy: Synthetic Data Generation with ‘synthpop’ in R</a>.</li>
</ul>
<p>By addressing missing data and outliers, we set a strong foundation for accurate and meaningful analysis, whether it’s univariate, bivariate, or multivariate.</p>
</section>
</section>
<section id="graphical-analysis-and-variable-distributions" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="graphical-analysis-and-variable-distributions"><span class="header-section-number">4.2</span> Graphical Analysis and Variable Distributions</h2>
<p>After examining the descriptive statistics, we now turn to graphical analysis to visually interpret the distribution of variables in the pre-exposure data from the <code>HbmassSynth</code> dataset. This section will leverage graphical methods such as histograms, box plots, and bar charts to illustrate the data’s distribution, central tendency, spread, and identify any potential outliers. These visualizations are crucial for revealing the underlying patterns and anomalies in the data, providing a deeper understanding of each variable’s characteristics.</p>
<section id="visualizing-quantitative-variables-with-histograms" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="visualizing-quantitative-variables-with-histograms"><span class="header-section-number">4.2.1</span> Visualizing Quantitative Variables with Histograms</h3>
<p>Histograms are a popular choice for visualizing continuous or quantitative variables. They offer a way to inspect the distribution, center, and spread of the data. By adjusting bin widths, we can control the granularity of the distribution visualization.</p>
<p>To create histograms for key continuous variables in the pre-exposure data, we can use ggplot2 along with customized bin widths to highlight distinct patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the dataset by removing rows with any non-finite values</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>pre_exposure_data <span class="ot">&lt;-</span> pre_exposure_data <span class="sc">%&gt;%</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), is.finite))</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dataframe to store variable names and bin widths</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>cont_var_distrib <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">var =</span> <span class="fu">c</span>(<span class="st">"BM"</span>, <span class="st">"FER"</span>, <span class="st">"FE"</span>, <span class="st">"TSAT"</span>, <span class="st">"TRANS"</span>, <span class="st">"AHBM"</span>, <span class="st">"RHBM"</span>),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">bin_width =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="fl">0.1</span>, <span class="dv">25</span>, <span class="fl">0.2</span>)  <span class="co"># Specify appropriate bin widths</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co"># List to store individual plots</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>histograms <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the dataframe to create plots for each variable</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(cont_var_distrib)) {</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  var_name <span class="ot">&lt;-</span> <span class="fu">as.character</span>(cont_var_distrib[i, <span class="st">"var"</span>])</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  bin_w <span class="ot">&lt;-</span> cont_var_distrib[i, <span class="st">"bin_width"</span>]</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="sc">!!</span><span class="fu">sym</span>(var_name))) <span class="sc">+</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> bin_w, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Distribution of"</span>, var_name))  <span class="co"># Plot title</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  histograms[[i]] <span class="ot">&lt;-</span> plot  <span class="co"># Store the plot in the list</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange the plots in a grid for a clearer visualization</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>gridExtra<span class="sc">::</span><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> histograms, <span class="at">ncol =</span> <span class="dv">3</span>)  <span class="co"># 3 columns of plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With this approach, we create histograms for the key continuous variables in a more automated way, allowing us to quickly understand their distributions.</p>
</section>
<section id="understanding-distribution-characteristics" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="understanding-distribution-characteristics"><span class="header-section-number">4.2.2</span> Understanding Distribution Characteristics</h3>
<p>After visualizing the distributions with histograms, it’s crucial to understand what these shapes and patterns tell us about our data. Certain characteristics of distributions are particularly informative:</p>
<ul>
<li><p><strong>Normal Distribution</strong>: A normal distribution, also known as a Gaussian distribution, is symmetrical and forms a bell-shaped curve when plotted. In a perfectly normal distribution, the mean, median, and mode are all equal, and data falls evenly on both sides of the mean.</p></li>
<li><p><strong>Skewness</strong>: Skewness measures the asymmetry of the probability distribution of a real-valued random variable.</p>
<ul>
<li><strong>Positive Skew (Right-skewed)</strong>: Most data falls to the left of the mean with a long tail extending to the right. The mean is typically greater than the median.</li>
<li><strong>Negative Skew (Left-skewed)</strong>: Most data falls to the right of the mean with a long tail extending to the left. The mean is typically less than the median.</li>
</ul></li>
<li><p><strong>Peakedness (Kurtosis)</strong>: Kurtosis measures the ‘tailedness’ of the distribution.</p>
<ul>
<li><strong>High Kurtosis (Leptokurtic)</strong>: Distributions with sharp peaks and heavy tails, indicating outliers.</li>
<li><strong>Low Kurtosis (Platykurtic)</strong>: Distributions with flatter peaks and thinner tails, suggesting a lack of outliers.</li>
<li><strong>Normal Kurtosis</strong>: Similar to the normal distribution, with a kurtosis value close to 3.</li>
</ul></li>
</ul>
<p>Understanding these concepts is essential for analyzing variable distributions because they can influence conclusions drawn from the data and the selection of appropriate statistical tests or models.</p>
</section>
<section id="analyzing-pre-exposure-variable-distributions" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="analyzing-pre-exposure-variable-distributions"><span class="header-section-number">4.2.3</span> Analyzing Pre-Exposure Variable Distributions</h3>
<p>Let’s compute and interpret skewness and kurtosis for our key variables to analyze their distribution characteristics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute skewness and kurtosis for each numeric variable</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>skewness_kurtosis <span class="ot">&lt;-</span> pre_exposure_data <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="fu">list</span>(</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Skewness =</span> <span class="sc">~</span><span class="fu">skewness</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Kurtosis =</span> <span class="sc">~</span><span class="fu">kurtosis</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="dv">3</span>  <span class="co"># Excess kurtosis</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  )))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the summary from wide to long format</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>skewness_kurtosis_long <span class="ot">&lt;-</span> skewness_kurtosis <span class="sc">%&gt;%</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Measurement"</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Measurement, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"Metric"</span>), <span class="at">sep =</span> <span class="st">"_"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">"Metric"</span>, <span class="at">values_from =</span> <span class="st">"Value"</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>skewness_kurtosis_long</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  Variable Skewness Kurtosis
  &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;
1 ID          0      -1.20  
2 BM          0.747   0.548 
3 FER         0.866   0.541 
4 FE          0.864   0.0895
5 TSAT        1.61    4.35  
6 TRANS      -0.226   0.705 
7 AHBM        0.520  -0.166 
8 RHBM       -0.212  -0.178 </code></pre>
</div>
</div>
<p>With skewness and kurtosis computed for each variable in our pre-exposure dataset, we can dive deeper into the distribution characteristics:</p>
<ul>
<li><p><strong>Body Mass (BM)</strong>: With a skewness of 0.747, BM displays a moderate right skew, suggesting the presence of athletes with higher body mass values in our sample. The kurtosis of 0.548 indicates a slightly more peaked distribution than normal, which might imply a greater variability of BM among athletes.</p></li>
<li><p><strong>Ferritin (FER)</strong>: The skewness value of 0.866 denotes a moderate right skew, indicating that some athletes have higher ferritin levels, which could reflect individual variations in iron metabolism or the effects of supplementation. The kurtosis close to zero suggests a distribution with tails similar to a normal distribution.</p></li>
<li><p><strong>Iron (FE)</strong>: Similar to FER, FE’s skewness of 0.864 shows a moderate right skew, which may correlate with individual differences in dietary intake or absorption. The low kurtosis value suggests a relatively normal distribution of tails, with no significant outliers.</p></li>
<li><p><strong>Transferrin Saturation (TSAT)</strong>: The skewness of 1.61 shows a more pronounced right skew, hinting at a subset of athletes with particularly high TSAT levels, potentially indicative of specific physiological or supplementation effects. The high kurtosis of 4.35 indicates a leptokurtic distribution, reflecting notable outliers or extreme values.</p></li>
<li><p><strong>Transferrin (TRANS)</strong>: The slight negative skewness of -0.226 might suggest a small number of athletes with lower transferrin levels. A kurtosis of 0.705 indicates a slightly leptokurtic distribution, with a modest presence of outliers.</p></li>
<li><p><strong>Absolute Hemoglobin Mass (AHBM)</strong>: A skewness of 0.520 suggests a mild right skew in AHBM levels among athletes. The negative kurtosis of -0.166 indicates a platykurtic distribution, which means the tails are lighter than a normal distribution, suggesting fewer extreme values.</p></li>
<li><p><strong>Relative Hemoglobin Mass (RHBM)</strong>: The small negative skewness of -0.212 indicates a distribution with a slight tail to the left. The negative kurtosis of -0.178 implies a distribution that is slightly flatter than normal, with a wide range of values relatively evenly distributed.</p></li>
</ul>
<p>By examining both skewness and kurtosis, we gain insights into not just the symmetry of our data distributions, but also the presence of outliers and the concentration of data around the mean. For instance, TSAT’s higher kurtosis and skewness might warrant further investigation into specific training or health interventions that could influence iron metabolism. Similarly, understanding the spread in BM could be vital for tailoring nutritional and training programs to individual athletes.</p>
<p>These distributional insights provide us with valuable clues about the underlying processes and variations within our athlete cohort. They guide us towards more targeted inquiries and help us tailor our analyses and recommendations to the specific needs and characteristics of our sample population.</p>
</section>
<section id="visualizing-quantitative-variables-with-box-plots" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="visualizing-quantitative-variables-with-box-plots"><span class="header-section-number">4.2.4</span> Visualizing Quantitative Variables with Box Plots</h3>
<p>Box plots are another method for visualizing the distribution and spread of continuous variables. They provide a concise summary of the minimum, 1st quartile, median, 3rd quartile, and maximum, along with identifying potential outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create box plots for the quantitative variables</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>box_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> AHBM)) <span class="sc">+</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Box Plot of Absolute Hemoglobin Mass (AHBM)"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(box_plot)  <span class="co"># Display the box plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="visualizing-categorical-variables-with-bar-plots" class="level3" data-number="4.2.5">
<h3 data-number="4.2.5" class="anchored" data-anchor-id="visualizing-categorical-variables-with-bar-plots"><span class="header-section-number">4.2.5</span> Visualizing Categorical Variables with Bar Plots</h3>
<p>For categorical variables, bar plots are commonly used to visualize the frequency or proportion of values in each category. This is useful for understanding the distribution of categorical data and identifying imbalances.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot for the categorical variable 'SEX'</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>bar_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> SEX)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"lightgreen"</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Sex in Pre-Exposure Data"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bar_plot)  <span class="co"># Display the bar plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This graphical univariate analysis provides an accessible and informative way to explore variable distributions in our pre-exposure dataset. These methods serve as the foundation for further analysis and can guide the direction of subsequent bivariate and multivariate analyses.</p>
</section>
<section id="comparing-pre-and-post-exposure-variable-distributions" class="level3" data-number="4.2.6">
<h3 data-number="4.2.6" class="anchored" data-anchor-id="comparing-pre-and-post-exposure-variable-distributions"><span class="header-section-number">4.2.6</span> Comparing Pre and Post Exposure Variable Distributions</h3>
<p>Building upon our understanding of the individual variable characteristics in the pre-exposure dataset, we now extend our graphical analysis to compare these distributions directly with their post-exposure counterparts. This comparison provides a visual assessment of the changes, if any, that occur in response to moderate altitude exposure and iron supplementation.</p>
<p>To facilitate this comparison, we overlaid histograms for key variables, color-coding the pre-exposure (skyblue) and post-exposure (salmon) data. This overlay offers a side-by-side distributional perspective, allowing us to observe shifts in central tendency, changes in variability, and the emergence or reduction of skewness.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a combined dataset with an additional column indicating the exposure type</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(pre_exposure_data, <span class="at">Exposure =</span> <span class="st">'Pre'</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(post_exposure_data, <span class="at">Exposure =</span> <span class="st">'Post'</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the variables and their corresponding bin widths</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BM"</span>, <span class="st">"FER"</span>, <span class="st">"FE"</span>, <span class="st">"TSAT"</span>, <span class="st">"TRANS"</span>, <span class="st">"AHBM"</span>, <span class="st">"RHBM"</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>bin_widths <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="fl">0.1</span>, <span class="dv">25</span>, <span class="fl">0.2</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty list to store plots</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>plots_list <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the variables to create overlay histograms</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(variables)) {</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  variable_name <span class="ot">&lt;-</span> variables[i]</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  bin_width <span class="ot">&lt;-</span> bin_widths[i]</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Generate the overlay histogram for the current variable using tidy evaluation</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> .data[[variable_name]], <span class="at">fill =</span> Exposure)) <span class="sc">+</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">data =</span> <span class="fu">filter</span>(combined_data, Exposure <span class="sc">==</span> <span class="st">'Pre'</span>), </span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>                   <span class="at">binwidth =</span> bin_width, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">'identity'</span>, <span class="at">color =</span> <span class="st">'black'</span>) <span class="sc">+</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">data =</span> <span class="fu">filter</span>(combined_data, Exposure <span class="sc">==</span> <span class="st">'Post'</span>), </span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>                   <span class="at">binwidth =</span> bin_width, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">'identity'</span>, <span class="at">color =</span> <span class="st">'black'</span>) <span class="sc">+</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Pre vs. Post Exposure: "</span>, variable_name)) <span class="sc">+</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Pre"</span> <span class="ot">=</span> <span class="st">"skyblue"</span>, <span class="st">"Post"</span> <span class="ot">=</span> <span class="st">"salmon"</span>)) <span class="sc">+</span></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add the plot to the list</span></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>  plots_list[[i]] <span class="ot">&lt;-</span> p</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange the generated plots in a grid</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>grid_plot <span class="ot">&lt;-</span> gridExtra<span class="sc">::</span><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> plots_list, <span class="at">ncol =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p><strong>Body Mass (BM)</strong>: The BM histograms show a consistent distribution between pre and post-exposure, suggesting that the exposure period did not significantly alter athletes’ body mass.</p></li>
<li><p><strong>Ferritin (FER)</strong>: There is a slight shift to the right in the post-exposure FER distribution, implying an increase in ferritin levels which could be attributed to the body’s response to altitude training or iron supplementation.</p></li>
<li><p><strong>Iron (FE)</strong>: The overlay indicates a similar distribution for FE levels with a slight increase in higher values post-exposure.</p></li>
<li><p><strong>Transferrin Saturation (TSAT)</strong>: Post-exposure, there appears to be a reduction in higher TSAT values, suggesting a possible utilization of iron stores during altitude exposure.</p></li>
<li><p><strong>Transferrin (TRANS)</strong>: The distributions before and after exposure are closely aligned, indicating stability in this variable across the study period.</p></li>
<li><p><strong>Absolute Hemoglobin Mass (AHBM)</strong>: The AHBM shows a slight increase in higher values post-exposure, which may reflect the physiological adaptations associated with altitude training aimed at increasing hemoglobin mass.</p></li>
<li><p><strong>Relative Hemoglobin Mass (RHBM)</strong>: The overlay suggests minimal changes in the distribution of RHBM, implying a consistent relative hemoglobin mass before and after exposure.</p></li>
</ul>
<p>With this visual approach, we’ve not only characterized individual variables but have also begun to uncover the narrative of how moderate altitude exposure may impact these athletes’ hematological profiles.</p>
</section>
</section>
</section>
<section id="bivariate-and-multivariate-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bivariate and Multivariate Analysis</h1>
<p>In sports science, uncovering the interplay between different physiological and performance-related variables can provide powerful insights. By analyzing relationships between two or more variables, we can better understand how they collectively influence athlete performance and adapt our training or nutrition programs accordingly.</p>
<section id="pairwise-scatter-plots" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="pairwise-scatter-plots"><span class="header-section-number">5.1</span> Pairwise Scatter Plots</h2>
<p>Pairwise scatter plots offer a visual examination of the relationship between two continuous variables. This form of analysis is pivotal for spotting trends, correlations, or outliers that could indicate a meaningful interaction affecting athlete outcomes.</p>
<p>For an expansive overview, we can create a grid of scatter plots that map the relationships between multiple variables simultaneously:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise scatter plots of continuous variables</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>cont_var_cols <span class="ot">&lt;-</span> pre_exposure_data[, <span class="fu">c</span>(<span class="st">"BM"</span>, <span class="st">"FER"</span>, <span class="st">"FE"</span>, <span class="st">"TSAT"</span>, <span class="st">"TRANS"</span>, <span class="st">"AHBM"</span>, <span class="st">"RHBM"</span>)]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(cont_var_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Alternatively, we can focus on individual relationships, such as body mass (BM) and ferritin (FER), to gain a more detailed understanding:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Individual pairwise scatter plot with body mass (BM) and ferritin (FER)</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> BM, <span class="at">y =</span> FER)) <span class="sc">+</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Pairwise Scatter Plot of BM and FER"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Both methods have their uses: the grid provides a broad snapshot suitable for initial explorations, while individual plots allow for a more concentrated look at specific interactions.</p>
</section>
<section id="correlation-matrix" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="correlation-matrix"><span class="header-section-number">5.2</span> Correlation Matrix</h2>
<p>The correlation matrix is an invaluable tool in sports science research, offering quantifiable evidence of how closely related different variables are. This can be crucial when identifying which factors might predict or influence an athlete’s performance and physiological responses. A correlation matrix provides a quick reference to understand these relationships and can guide further, more focused analysis.</p>
<p>Here’s how we compute and visualize the correlation matrix using our pre-exposure data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Computing the correlation matrix for selected variables</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(pre_exposure_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(BM, FER, FE, TSAT, TRANS, AHBM, RHBM), <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing the correlation matrix with a circle representation</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"circle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Each cell in the matrix represents the correlation coefficient between two variables, ranging from -1 (perfect negative correlation) to +1 (perfect positive correlation), with 0 indicating no linear relationship. This visual approach allows practitioners to quickly identify which variables warrant further scrutiny and analysis.</p>
<p>Analysing our example dataset, we see that a prominent dark blue circle between AHBM and BM indicates a strong positive correlation, suggesting that body mass may influence absolute hemoglobin mass, a vital parameter for athlete endurance. This strong association merits further exploration to understand its implications on performance.</p>
<p>Conversely, the red circle between AHBM and TRANS points to a notable negative correlation, hinting at an inverse relationship between hemoglobin mass and transferrin levels. This inverse correlation could lead to inquiries about how iron transport proteins are modulated in response to endurance training.</p>
<p>This correlation matrix visualizes which pairs of variables have stronger linear relationships and may thus be key focal points for developing strategies to optimize athlete health and performance in response to training stimuli.</p>
</section>
<section id="investigating-relationships-with-the-dependent-variable" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="investigating-relationships-with-the-dependent-variable"><span class="header-section-number">5.3</span> Investigating Relationships with the Dependent Variable</h2>
<p>In exploring bivariate relationships, it’s particularly insightful to look at how various independent variables relate to a dependent variable of interest. For sports scientists, understanding factors that potentially influence key metrics like absolute hemoglobin mass (AHBM) can directly inform training and health strategies.</p>
<p>Let’s illustrate this with a scatter plot examining the relationship between ferritin levels (FER) and AHBM:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of ferritin (FER) against absolute hemoglobin mass (AHBM)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> FER, <span class="at">y =</span> AHBM)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relationship Between FER and AHBM"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot not only depicts individual data points but also includes a trend line that summarizes the relationship between FER and AHBM, complete with a shaded area representing the standard error. Such visualizations can highlight potential predictive variables or areas that may benefit from targeted interventions.</p>
</section>
<section id="visualizing-three-way-relationships" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="visualizing-three-way-relationships"><span class="header-section-number">5.4</span> Visualizing Three-Way Relationships</h2>
<p>By incorporating additional variables into our bivariate plots, we can observe the dynamics of three-way relationships. Such insights are particularly valuable in sports science, where factors like sex can influence physiological responses to training.</p>
<p>Consider the relationship between transferrin (TRANS), absolute hemoglobin mass (AHBM), and sex (SEX). These three variables can interact in complex ways that might impact an athlete’s ability to process and utilize iron — a critical component for oxygen delivery and endurance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three-way relationship between transferrin (TRANS), AHBM, and SEX</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> TRANS, <span class="at">y =</span> AHBM, <span class="at">color =</span> <span class="fu">as.factor</span>(SEX))) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>  <span class="co"># Scatter plot points</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span>  <span class="co"># Linear model fit line with standard error</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"skyblue"</span>, <span class="st">"salmon"</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">name =</span> <span class="st">"Sex"</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Three-Way Relationship between TRANS, AHBM, and SEX"</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()  <span class="co"># Clean classic theme for better readability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot reveals a divergent relationship between transferrin (TRANS) and absolute hemoglobin mass (AHBM) across sexes. For female athletes, there is a positive trend where AHBM increases with higher TRANS levels. Conversely, male athletes exhibit a negative trend, with AHBM decreasing as TRANS levels rise. This contrast highlights the importance of considering sex-specific physiological responses in sports science research and training regimens.</p>
</section>
<section id="handling-associated-variables-and-covariance" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="handling-associated-variables-and-covariance"><span class="header-section-number">5.5</span> Handling Associated Variables and Covariance</h2>
<p>In sports science, understanding the association between variables is vital for predicting outcomes such as performance or recovery times. Association means that knowledge about the value of one variable gives some information about the value of another. For instance, the number of hours spent training may be associated with improvements in endurance performance.</p>
<p>Covariance provides a measure of how much two variables change together. If the covariance is positive, it indicates that as one variable increases, the other tends to increase as well. A negative covariance implies an inverse relationship. Unlike correlation, covariance does not have a standardized range, so it cannot convey the strength of the relationship, only its direction. In contrast, correlation normalizes the covariance to a value between -1 and 1, providing a clearer indication of how strong the relationship is. In R, we can calculate covariance using the <code>cov()</code> function from the <code>stats</code> package.</p>
</section>
<section id="exploring-non-linear-associations" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="exploring-non-linear-associations"><span class="header-section-number">5.6</span> Exploring Non-linear Associations</h2>
<p>Correlation and covariance are measures of linear association, meaning they can only capture straight-line relationships. Non-linear associations, where changes in one variable relate to non-proportional changes in another, require different analytical approaches. For example, the effect of training intensity on injury risk might be non-linear, with risk plateauing or even decreasing after a certain point.</p>
<p>Scatter plots are a simple yet effective way to visualize potential non-linear relationships. If the pattern of points on the plot isn’t straight, it might indicate a non-linear association. For plotting these relationships, <code>ggplot2</code> provides an excellent toolset with functions like <code>geom_point()</code> and <code>geom_smooth()</code> for a smooth curve that captures the nature of the non-linear relationship.</p>
</section>
<section id="contingency-tables-and-chi-square-statistics" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="contingency-tables-and-chi-square-statistics"><span class="header-section-number">5.7</span> Contingency Tables and Chi-Square Statistics</h2>
<p>Contingency tables are a way of summarizing the relationship between categorical variables. They display the frequency distribution of variables and can reveal patterns that suggest associations. For example, injury rates might differ between athletes of different age groups.</p>
<p>The Chi-Square statistic is a measure derived from contingency tables, used to assess whether observed frequencies differ from expected frequencies — essentially testing for an association between categorical variables. In R, the <code>chisq.test()</code> function in the <code>stats</code> package provides an easy way to calculate this statistic.</p>
<p>Each of these statistical concepts mentioned in the three subsections above allows sports scientists to delve deeper into their data, uncovering relationships that might not be immediately apparent and providing a more nuanced understanding of the factors that contribute to athletic performance and well-being.</p>
</section>
<section id="visual-comparisons-of-groups" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="visual-comparisons-of-groups"><span class="header-section-number">5.8</span> Visual Comparisons of Groups</h2>
<p>When exploring the data, it’s beneficial to compare groups visually. Side-by-side box plots and overlaid histograms are particularly effective for this purpose. They allow us to compare the central tendency and variability of a quantitative variable across different categories of a related factor. For sports and exercise scientists, these visualizations can highlight how different treatments or conditions affect athlete physiology.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Side-by-side box plots of AHBM across different levels of iron supplementation (SUP_DOSE)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pre_exposure_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(SUP_DOSE, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"105 mg"</span>, <span class="st">"210 mg"</span>)), <span class="at">y =</span> AHBM)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Iron Supplementation Dose"</span>, <span class="at">y =</span> <span class="st">"Absolute Hemoglobin Mass"</span>, <span class="at">title =</span> <span class="st">"AHBM Across Different Levels of Iron Supplementation"</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Data_Exploration_Techniques_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The box plots reveal that athletes not receiving any iron supplementation have a wider range and higher median of absolute hemoglobin mass (AHBM) compared to those receiving supplementation. Athletes receiving 105 mg of iron show a tighter distribution of AHBM, whereas those on a higher dose of 210 mg exhibit the lowest median AHBM. This suggests a potential inverse relationship between the dose of iron supplementation and hemoglobin mass, worthy of further investigation.</p>
<p>To conclude this section, bivariate and multivariate analyses are key in uncovering the multifaceted relationships inherent in sports science data. They lay the groundwork for hypothesis formation and deeper investigation, ultimately guiding targeted interventions and informed decision-making.</p>
</section>
</section>
<section id="conclusion-and-reflection" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion and Reflection</h1>
<p>In this lesson, we’ve delved deeply into Exploratory Data Analysis (EDA), a cornerstone of effective data utilization in sport science. We explored various techniques to analyze and visualize data, uncovering underlying structures and vital insights that influence athlete performance and health.</p>
<p>Through the use of R and its extensive toolkit for EDA, we’ve demonstrated how to interpret complex data sets, identify trends, and assess the impact of variables like altitude and supplementation on athlete health. This process has not only enhanced our understanding of data analysis techniques but also highlighted the dynamic nature of EDA in adapting to new data and evolving research questions.</p>
<p>As you continue to apply these EDA strategies to your own sport science projects, you’ll find they are indispensable for making informed decisions and fostering evidence-based practices. Each skill refined and insight gained through this lesson adds a layer of sophistication to your analytical capabilities, setting the stage for future discoveries and innovations in the field.</p>
</section>
<section id="knowledge-spot-check" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Knowledge Spot-Check</h1>
<div class="callout callout-style-default callout-tip callout-titled" title="**What is the primary purpose of Exploratory Data Analysis (EDA) in sport science?** <br> <br> A) To confirm existing hypotheses. <br> B) To detect patterns and test assumptions without prior hypotheses. <br> C) To present finalized research findings. <br> D) To produce detailed statistical models. <br> <br> Expand to see the correct answer.">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>What is the primary purpose of Exploratory Data Analysis (EDA) in sport science?</strong> <br> <br> A) To confirm existing hypotheses. <br> B) To detect patterns and test assumptions without prior hypotheses. <br> C) To present finalized research findings. <br> D) To produce detailed statistical models. <br> <br> Expand to see the correct answer.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is B) To detect patterns and test assumptions without prior hypotheses.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="**Which R package did we use to load the `HbmassSynth` dataset?** <br> <br> A) ggplot2 <br> B) dplyr <br> C) skimr <br> D) speedsR <br> <br> Expand to see the correct answer.">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Which R package did we use to load the <code>HbmassSynth</code> dataset?</strong> <br> <br> A) ggplot2 <br> B) dplyr <br> C) skimr <br> D) speedsR <br> <br> Expand to see the correct answer.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is D) speedsR.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="**Why is it important to assess skewness and kurtosis in data distributions during EDA?** <br> <br> A) To determine the correct application of linear models. <br> B) To understand the symmetry and tail behavior of the distribution. <br> C) To ensure the data fits within a specific size limit. <br> D) To enhance the visual appeal of data plots. <br> <br> Expand to see the correct answer.">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Why is it important to assess skewness and kurtosis in data distributions during EDA?</strong> <br> <br> A) To determine the correct application of linear models. <br> B) To understand the symmetry and tail behavior of the distribution. <br> C) To ensure the data fits within a specific size limit. <br> D) To enhance the visual appeal of data plots. <br> <br> Expand to see the correct answer.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is B) To understand the symmetry and tail behavior of the distribution.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="**What does a correlation matrix help identify in sport science data analysis?** <br> <br> A) Outliers and anomalies only. <br> B) The strength and direction of relationships between variables. <br> C) The exact predictive models to be used. <br> D) The best graphical representation. <br> <br> Expand to see the correct answer.">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>What does a correlation matrix help identify in sport science data analysis?</strong> <br> <br> A) Outliers and anomalies only. <br> B) The strength and direction of relationships between variables. <br> C) The exact predictive models to be used. <br> D) The best graphical representation. <br> <br> Expand to see the correct answer.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is B) The strength and direction of relationships between variables.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="**Why are overlay histograms useful when comparing pre and post intervention data?** <br> <br> A) They confirm the data is error-free. <br> B) They show changes in data distributions over time. <br> C) They reduce the data set size. <br> D) They automate the data cleaning process. <br> <br> Expand to see the correct answer.">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Why are overlay histograms useful when comparing pre and post intervention data?</strong> <br> <br> A) They confirm the data is error-free. <br> B) They show changes in data distributions over time. <br> C) They reduce the data set size. <br> D) They automate the data cleaning process. <br> <br> Expand to see the correct answer.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is B) They show changes in data distributions over time.</p>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="Data_Exploration_Techniques_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>